config/routes.rb
Rails.application.routes.draw do
  resource :game, only: [:new, :update]
  root 'root#index'
end

app/models/game.rb
class Game
  attr_accessor :size, :table, :player, :movements, :table_size

  NEUTRO    = '-'
  PLAYER_1  = 'X'
  PLAYER_2  = 'O'
  PLAYERS   = [PLAYER_1, PLAYER_2]

  def initialize(size = 3)
    self.size = size.to_i
    self.table_size = @size * @size
    self.player = PLAYERS.sample
    self.table = Array.new(table_size, NEUTRO)
    self.movements = []
    move(initial_position) if player == PLAYER_2
  end

  def update(params)
    self.player = params[:player]
    self.table = params[:table]
    move(params[:position].to_i)
    auto_move unless end?
  end

  def win?(cell_player)
    winning_lines.any? do |line|
      line.all? { |line_cell| line_cell == cell_player }
    end
  end

  def blocked?
    winning_lines.all? do |line|
      line.any? { |line_cell| line_cell == PLAYER_1 } && line.any? { |line_cell| line_cell == PLAYER_2 }
    end
  end

  def end?
    win?(PLAYER_1) || win?(PLAYER_2) || @table.count(NEUTRO) == 0
  end

  private

  def initial_position
    size == 3 ? 4 : 0
  end

  def move(position)
    self.table[position] = player
    self.player = other_player
    self.movements << position
    self
  end

  def other_player
    player == PLAYER_1 ? PLAYER_2 : PLAYER_1
  end

  def auto_move
    move(best_move)
  end

  def best_move
    available_positions.send(best_move_operation_by_player) { |position| minimax(position) }
  end

  def available_positions
    table.map.with_index { |player_in_cell, position| player_in_cell == NEUTRO ? position : nil }.compact
  end

  def winning_lines
    (
      (0..table_size.pred).each_slice(size).to_a +
      (0..table_size.pred).each_slice(size).to_a.transpose +
      [ (0..table_size.pred).step(size.succ).to_a ] +
      [ (size.pred..(table_size-size)).step(size.pred).to_a ]
    ).map { |line| line.map { |position| table[position] }}
  end

  def minimax(position = nil)
    move(position) if position
    leaf_value = evaluate_leaf
    return leaf_value if leaf_value
    available_positions_operation
  ensure
    unmove if position
  end

  def evaluate_leaf
    return  100 if win?(PLAYER_1)
    return -100 if win?(PLAYER_2)
    return    0 if blocked?
  end

  def available_positions_operation
    available_positions.map do |position|
      minimax(position).send(minimax_operation_by_player, movements.count + 1)
    end.send(possible_move_operation_by_player)
  end

  def unmove
    self.table[movements.pop.to_i] = NEUTRO
    self.player = other_player
    self
  end

  def minimax_operation_by_player
    player == PLAYER_1 ? :- : :+
  end

  def possible_move_operation_by_player
    player == PLAYER_1 ? :max : :min
  end

  def best_move_operation_by_player
    player == PLAYER_1 ? :max_by : :min_by
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :setup_game

  # GET /games/new
  def new
    respond_to do |format|
      format.js
      format.html { redirect_to root_url }
    end
  end

  # PUT /game
  def update
    @game.update(permitted_params(:update))
  end

  private

  def setup_game
    @game = Game.new(params[:size])
  end

  def permitted_params(action = :create)
    params.permit(:player, :position, table: [])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  # GET /
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_game.html.erb
<% i = 0 %>
<div class="row justify-content-center">
  <div class="col-6">
    <table id="grid" class="table table-bordered" data-size="<%= @game.size %>">
      <tbody>
        <% @game.size.times do -%>
          <tr>
            <% @game.size.times do -%>
              <% player = @game.table[i] %>
              <td class="active text-center" data-position="<%= i %>"><span class="cell <%= player %>"><%= player == Game::NEUTRO ? '&nbsp;'.html_safe : player %></span></td>
              <% i += 1 %>
            <% end -%>
          </tr>
        <% end -%>
      </tbody>
    </table>
  </div>
</div>

<% if @game.end? %>
  <div class="row justify-content-center">
    <%= button_to "Restart", new_game_path, remote: true, method: :get, data: { disable_with: 'loading game...' }, params: { size: @game.size }, class: 'btn btn-primary' %>
  </div>
  <% if @game.win?(Game::PLAYER_1) %>
    <script>display_message("PLAYER WON!", 'success'); show_background("<%= Game::PLAYER_1 %>");</script>
  <% elsif @game.win?(Game::PLAYER_2) %>
    <script>display_message("COMPUTER WON!", 'danger'); show_background("<%= Game::PLAYER_2 %>");</script>
  <% else %>
    <script>display_message("IT'S A DRAW!", 'warning')</script>
  <% end %>
  <script>$('td.active').removeClass('active');</script>
<% end %>

app/views/games/new.js.erb
<% if @game.size.blank? -%>
display_message('Game size no specified!', 'danger');
<% else -%>
$("#game").html("<%= escape_javascript(render 'game') %>")
<% end -%>

app/views/games/update.js.erb
$("#game").html("<%= escape_javascript(render 'game') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tic Tac Toe App</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>

      <hr>
      <footer class="footer">
        <p>© Tic Tac Toe App 2017</p>
      </footer>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:scripts) %>
  </body>
</html>

app/views/root/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Tic Tac Toe App</h1>
</div>

<hr>

<div class="row justify-content-md-center">
  <div class="col-md-auto">
    <%= button_to "3 x 3", new_game_path, remote: true, method: :get, data: { disable_with: 'loading game...' }, params: { size: 3 }, class: 'btn btn-primary' %>
  </div>
  <!-- <div class="col-md-auto">
    <%= button_to "4 x 4", new_game_path, remote: true, method: :get, data: { disable_with: 'loading game...' }, params: { size: 4 }, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-auto">
    <%= button_to "5 x 5", new_game_path, remote: true, method: :get, data: { disable_with: 'loading game...' }, params: { size: 5 }, class: 'btn btn-primary' %>
  </div> -->
</div>

<hr>

<div class="card">
  <div id="loader" class="card-block">
    <div class="loader"></div>
  </div>
  <div id="game" class="card-block">
    <p class="text-center display-3 text-danger">Please select game size above!</p>
  </div>
</div>

<% content_for :scripts do -%>
<script>
  var PLAYER_1 = '<%= Game::PLAYER_1 %>';
  var PLAYER_2 = '<%= Game::PLAYER_2 %>';
  var NEUTRO = '<%= Game::NEUTRO %>';
  var GAME_URL = '<%= game_path %>';
</script>
<% end -%>